grab 0.2.1

diff --git a/grab b/grab
--- a/grab
+++ b/grab
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-VER="0.2.0"
+VER="0.2.1"
 
 GR="\033[0;36m"
 RD="\033[0;31m"
@@ -40,6 +40,8 @@ fi
 
 # grab list of released files from github
 lst=$(curl -s "https://api.github.com/repos/${u}/releases/latest" | grep "browser_download_url" | grep "${e}" |  cut -d '"' -f 4 | xargs -n1 basename)
+
+[ $? -ne 0 ] && { err "unable to find eligible files in the latest release of this repository"; exit 1; }
 
 echo -e "\nchoose the version you would like to install:"
 select choice in ${lst}; do
